### PR TITLE
Add Simplified Chinese translations

### PR DESCRIPTION
**Pull request by luluxie**
Almost done, add translations for Simplified Chinese users.

### CODE REVIEW

**Comment by guidefloripa** [comment]
Good Job. Now we need to know how to write 'Chinese' (the language) in chinese and your name to put in ocenaudio

**Comment by luluxie** [comment]
@guidefloripa thank you for the quick response. This bundle is for 'Simplified Chinese' language which writes ‘简体中文’ in simplified chinese. There are also Traditional Chinese languages for different regions, so don't be confused, you'd better use 'Simplified Chinese' for this pull request, not simply 'Chinese'. 
My name is Lulu Xie.

**Comment by luluxie** [comment]
By the way, is there a way I can test the translations with my local ocenaudio installation?

**Comment by guidefloripa** [comment]
You could write us in http://www.ocenaudio.com/feedback and we'll send you a test version of ocenaudio.
Please, don't forget to mention what OS you are using.

**Pull request merged**
