### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by JoHongsik**

### CODE REVIEW

**Comment by guidefloripa** [comment]
For merging into main repository, first you need to solve the conflict files.

**Comment by JoHongsik** [comment]
i can't catch what the problem is. could you let me know how i can solve it?

**Comment by guidefloripa** [comment]
The problem is because you renamed the files from the **base** folder. Now it conflicts because these files were removed (they should not be touched). One solution would be you delete your ocenaudio-translations repository and fork it again just copying the ko_KR files into this new fork.

**Comment by guidefloripa** [comment]
Anyway, if you don't want to do this, I could commit the ko_KR files in this main repository mentioning your account.

**Comment by guidefloripa** [comment]
Please, check the following translation on **qtocen.ts**: "You can drop audio files, folders, archives, urls and playlists."

**Comment by JoHongsik** [comment]
you can commit ko_KR file mentioning my account. after you commit, i am going to fork again and edit what you mentioned.

**Comment by guidefloripa** [comment]
We have updated the master branch. Please, fork this repo again and fix the string we mentioned. One last thing, contact us in http://www.ocenaudio.com/feedback for getting a beta version with the korean translation.

**Comment by JoHongsik** [comment]
ok, i will

**Pull request closed without merging**
